/**
 * Kenya Counties, Constituencies, and Wards Data
 * For searchable location selection in property registration
 */

export const KENYA_COUNTIES = [
  "Baringo",
  "Bomet",
  "Bungoma",
  "Busia",
  "Elgeyo-Marakwet",
  "Embu",
  "Garissa",
  "Homa Bay",
  "Isiolo",
  "Kajiado",
  "Kakamega",
  "Kericho",
  "Kiambu",
  "Kilifi",
  "Kirinyaga",
  "Kisii",
  "Kisumu",
  "Kitui",
  "Kwale",
  "Laikipia",
  "Lamu",
  "Machakos",
  "Makueni",
  "Mandera",
  "Marsabit",
  "Meru",
  "Migori",
  "Mombasa",
  "Murang'a",
  "Nairobi",
  "Nakuru",
  "Nandi",
  "Narok",
  "Nyamira",
  "Nyandarua",
  "Nyeri",
  "Samburu",
  "Siaya",
  "Taita-Taveta",
  "Tana River",
  "Tharaka-Nithi",
  "Trans Nzoia",
  "Turkana",
  "Uasin Gishu",
  "Vihiga",
  "Wajir",
  "West Pokot",
];

// Sample constituencies for major counties (can be expanded)
export const CONSTITUENCIES_BY_COUNTY: Record<string, string[]> = {
  "Nairobi": [
    "Westlands",
    "Dagoretti North",
    "Dagoretti South",
    "Langata",
    "Kibra",
    "Roysambu",
    "Kasarani",
    "Ruaraka",
    "Embakasi South",
    "Embakasi North",
    "Embakasi Central",
    "Embakasi East",
    "Embakasi West",
    "Makadara",
    "Kamukunji",
    "Starehe",
    "Mathare",
  ],
  "Kiambu": [
    "Gatundu South",
    "Gatundu North",
    "Juja",
    "Thika Town",
    "Ruiru",
    "Githunguri",
    "Kiambu",
    "Kiambaa",
    "Kabete",
    "Kikuyu",
    "Limuru",
    "Lari",
  ],
  "Mombasa": [
    "Changamwe",
    "Jomvu",
    "Kisauni",
    "Nyali",
    "Likoni",
    "Mvita",
  ],
  "Nakuru": [
    "Nakuru Town East",
    "Nakuru Town West",
    "Bahati",
    "Gilgil",
    "Kuresoi North",
    "Kuresoi South",
    "Molo",
    "Naivasha",
    "Njoro",
    "Rongai",
    "Subukia",
  ],
  "Kisumu": [
    "Kisumu East",
    "Kisumu West",
    "Kisumu Central",
    "Seme",
    "Nyando",
    "Muhoroni",
    "Nyakach",
  ],
};

// Sample wards for major constituencies (can be expanded)
export const WARDS_BY_CONSTITUENCY: Record<string, string[]> = {
  "Westlands": [
    "Kitisuru",
    "Parklands/Highridge",
    "Karura",
    "Kangemi",
    "Mountain View",
  ],
  "Dagoretti North": [
    "Kilimani",
    "Kawangware",
    "Gatina",
    "Kileleshwa",
    "Kabiro",
  ],
  "Langata": [
    "Karen",
    "Nairobi West",
    "Mugumo-ini",
    "South C",
    "Nyayo Highrise",
  ],
  "Embakasi South": [
    "Imara Daima",
    "Kwa Njenga",
    "Kwa Reuben",
    "Pipeline",
    "Kware",
  ],
  "Embakasi East": [
    "Upper Savannah",
    "Lower Savannah",
    "Embakasi",
    "Utawala",
    "Mihang'o",
  ],
  "Kasarani": [
    "Clay City",
    "Mwiki",
    "Kasarani",
    "Njiru",
    "Ruai",
  ],
  "Ruiru": [
    "Biashara",
    "Gatongora",
    "Kahawa Sukari",
    "Kahawa Wendani",
    "Kiuu",
    "Mwihoko",
    "Mwiki",
  ],
};
